_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 37
                - 41
                - 49
                - 51
                - 55
                - 63
                - 71
                - 83
            "2":
                - 1
                - 37
                - 41
                - 49
                - 51
                - 55
                - 63
                - 71
                - 83
            "3":
                - 5
                - 23
                - 24
                - 55
                - 61
                - 62
            "4": 3.9.20
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
